In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [3]:
!pip install pyspark

Requirement already satisfied: pyspark in /usr/local/lib/python3.10/dist-packages (3.5.3)
Requirement already satisfied: py4j==0.10.9.7 in /usr/local/lib/python3.10/dist-packages (from pyspark) (0.10.9.7)

In [4]:
import pyspark
from pyspark.sql import SparkSession
spark = SparkSession.builder.appName('Weather').getOrCreate()

In [25]:
from pyspark.sql.functions import *
from pyspark.sql.types import *
from pyspark.sql import types as T
from pyspark.sql.window import Window

In [6]:
df = spark.read.csv('/content/drive/MyDrive/BDA_1_Sem/ABD/ABD_Lab/Hadoop/Pyspark/Spark3/Weather Data in India from 1901 to 2017.csv', header = True, inferSchema = True)
df.show()

+---+----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+
|_c0|YEAR|  JAN|  FEB|  MAR|  APR|  MAY|  JUN|  JUL|  AUG|  SEP|  OCT|  NOV|  DEC|
+---+----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+
|  0|1901|17.99|19.43|23.49|26.41|28.28| 28.6|27.49|26.98|26.26|25.08|21.73|18.95|
|  1|1902| 19.0|20.39| 24.1|26.54|28.68|28.44|27.29|27.05|25.95|24.37|21.33|18.78|
|  2|1903|18.32|19.79|22.46|26.03|27.93|28.41|28.04|26.63|26.34|24.57|20.96|18.29|
|  3|1904|17.77|19.39|22.95|26.73|27.83|27.85|26.84|26.73|25.84|24.36|21.07|18.84|
|  4|1905| 17.4|17.79|21.78|24.84|28.32|28.69|27.67|27.47|26.29|26.16|22.07|18.71|
|  5|1906| 17.5|19.14|22.21|26.53|29.06|28.02|27.46|26.82|26.23|24.75|21.93|19.55|
|  6|1907|19.27|19.42|22.03|26.98|27.52|27.66|27.28|26.38|26.26|24.72|22.11|18.46|
|  7|1908|18.35|19.73|22.93|27.06|28.07|28.49|27.16|26.41|25.74|24.25|21.06|18.15|
|  8|1909|17.79|19.05| 23.4|25.76|27.97|27.67|26.56|26.43|25.47|24.37|22.01|18.86|
|  9|1910|18.14|19.72| 22.9|25.96|28.36|27.72|26.93|26.61|25.98|24.04|20.72|18.05|
| 10|1911|18.52|19.18|22.05| 26.0|28.55|28.02|27.44|27.04|26.22|24.57| 21.1|18.76|
| 11|1912| 18.6|20.84|22.93|26.21| 28.3|28.53|27.49|26.68|25.81|24.44| 21.0|18.44|
| 12|1913| 18.2|19.98|22.15|26.61|27.95|27.91| 27.0| 26.8|26.02|24.35|20.92| 18.7|
| 13|1914|18.96|19.66|22.63|25.73|28.24|28.46|27.29|26.49|26.38|23.97|21.87|18.73|
| 14|1915|17.93| 19.0|22.69|26.23|29.17|28.58|27.77|27.32|26.82|25.46|22.18|18.31|
| 15|1916|18.52|19.68|24.24|26.84|28.16|27.81|27.08|26.77| 26.0| 24.6|21.03|18.17|
| 16|1917|18.16|19.94|22.46|25.29|26.97|27.41|27.15|26.64|25.79|23.85| 20.8|18.39|
| 17|1918|17.25|19.58|22.64|25.26|28.27|27.58|27.74|26.97| 26.0|24.54|21.71|18.37|
| 18|1919|18.78|19.15|23.15|26.19| 28.2| 28.3|27.28|26.84|25.84|24.36|21.48|18.58|
| 19|1920|18.27|19.16|23.02|25.73|27.06|27.76|27.48|26.61|26.34|24.85|21.84|18.78|
+---+----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+
only showing top 20 rows

In [7]:
df.printSchema()

root
 |-- _c0: integer (nullable = true)
 |-- YEAR: integer (nullable = true)
 |-- JAN: double (nullable = true)
 |-- FEB: double (nullable = true)
 |-- MAR: double (nullable = true)
 |-- APR: double (nullable = true)
 |-- MAY: double (nullable = true)
 |-- JUN: double (nullable = true)
 |-- JUL: double (nullable = true)
 |-- AUG: double (nullable = true)
 |-- SEP: double (nullable = true)
 |-- OCT: double (nullable = true)
 |-- NOV: double (nullable = true)
 |-- DEC: double (nullable = true)

Q1) Add column average temperature for each year

In [8]:
df1 = df.withColumn('Average Temperature', (df['Jan'] + df['Feb'] + df['Mar'] + df['Apr'] + df['May'] + df['Jun'] + df['Jul'] + df['Aug'] + df['Sep'] + df['Oct'] + df['NOV'] + df['Dec'])/12)
df1.show()

+---+----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-------------------+
|_c0|YEAR|  JAN|  FEB|  MAR|  APR|  MAY|  JUN|  JUL|  AUG|  SEP|  OCT|  NOV|  DEC|Average Temperature|
+---+----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-------------------+
|  0|1901|17.99|19.43|23.49|26.41|28.28| 28.6|27.49|26.98|26.26|25.08|21.73|18.95| 24.224166666666665|
|  1|1902| 19.0|20.39| 24.1|26.54|28.68|28.44|27.29|27.05|25.95|24.37|21.33|18.78| 24.326666666666664|
|  2|1903|18.32|19.79|22.46|26.03|27.93|28.41|28.04|26.63|26.34|24.57|20.96|18.29| 23.980833333333333|
|  3|1904|17.77|19.39|22.95|26.73|27.83|27.85|26.84|26.73|25.84|24.36|21.07|18.84| 23.849999999999998|
|  4|1905| 17.4|17.79|21.78|24.84|28.32|28.69|27.67|27.47|26.29|26.16|22.07|18.71|            23.9325|
|  5|1906| 17.5|19.14|22.21|26.53|29.06|28.02|27.46|26.82|26.23|24.75|21.93|19.55| 24.099999999999998|
|  6|1907|19.27|19.42|22.03|26.98|27.52|27.66|27.28|26.38|26.26|24.72|22.11|18.46| 24.007499999999997|
|  7|1908|18.35|19.73|22.93|27.06|28.07|28.49|27.16|26.41|25.74|24.25|21.06|18.15|              23.95|
|  8|1909|17.79|19.05| 23.4|25.76|27.97|27.67|26.56|26.43|25.47|24.37|22.01|18.86| 23.778333333333336|
|  9|1910|18.14|19.72| 22.9|25.96|28.36|27.72|26.93|26.61|25.98|24.04|20.72|18.05| 23.760833333333338|
| 10|1911|18.52|19.18|22.05| 26.0|28.55|28.02|27.44|27.04|26.22|24.57| 21.1|18.76| 23.954166666666666|
| 11|1912| 18.6|20.84|22.93|26.21| 28.3|28.53|27.49|26.68|25.81|24.44| 21.0|18.44| 24.105833333333337|
| 12|1913| 18.2|19.98|22.15|26.61|27.95|27.91| 27.0| 26.8|26.02|24.35|20.92| 18.7| 23.882500000000004|
| 13|1914|18.96|19.66|22.63|25.73|28.24|28.46|27.29|26.49|26.38|23.97|21.87|18.73| 24.034166666666668|
| 14|1915|17.93| 19.0|22.69|26.23|29.17|28.58|27.77|27.32|26.82|25.46|22.18|18.31| 24.288333333333338|
| 15|1916|18.52|19.68|24.24|26.84|28.16|27.81|27.08|26.77| 26.0| 24.6|21.03|18.17| 24.075000000000003|
| 16|1917|18.16|19.94|22.46|25.29|26.97|27.41|27.15|26.64|25.79|23.85| 20.8|18.39|  23.57083333333333|
| 17|1918|17.25|19.58|22.64|25.26|28.27|27.58|27.74|26.97| 26.0|24.54|21.71|18.37| 23.825833333333332|
| 18|1919|18.78|19.15|23.15|26.19| 28.2| 28.3|27.28|26.84|25.84|24.36|21.48|18.58| 24.012500000000003|
| 19|1920|18.27|19.16|23.02|25.73|27.06|27.76|27.48|26.61|26.34|24.85|21.84|18.78|  23.90833333333333|
+---+----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-------------------+
only showing top 20 rows

Q2) Add row average temperature of each month

In [24]:
avg_temperatures = df.select([avg(col(month)).alias(month) for month in df.columns[2:]]).first()

schema = T.StructType([
    T.StructField("_c0", T.IntegerType(), True),
    T.StructField("YEAR", T.IntegerType(), True),
    T.StructField("JAN", T.DoubleType(), True),
    T.StructField("FEB", T.DoubleType(), True),
    T.StructField("MAR", T.DoubleType(), True),
    T.StructField("APR", T.DoubleType(), True),
    T.StructField("MAY", T.DoubleType(), True),
    T.StructField("JUN", T.DoubleType(), True),
    T.StructField("JUL", T.DoubleType(), True),
    T.StructField("AUG", T.DoubleType(), True),
    T.StructField("SEP", T.DoubleType(), True),
    T.StructField("OCT", T.DoubleType(), True),
    T.StructField("NOV", T.DoubleType(), True),
    T.StructField("DEC", T.DoubleType(), True)
])

new_row_data = [(None, None, avg_temperatures[0], avg_temperatures[1],
                 avg_temperatures[2], avg_temperatures[3], avg_temperatures[4],
                 avg_temperatures[5], avg_temperatures[6], avg_temperatures[7],
                 avg_temperatures[8], avg_temperatures[9], avg_temperatures[10],
                 avg_temperatures[11])]

new_row_df = spark.createDataFrame(new_row_data, schema=schema)
df_combined = new_row_df.union(df)
df_combined = df_combined.orderBy("YEAR")
df_combined.show()

+----+----+-----------------+------------------+------------------+------------------+------------------+------------------+------------------+------------------+------------------+------------------+------------------+------------------+
| _c0|YEAR|              JAN|               FEB|               MAR|               APR|               MAY|               JUN|               JUL|               AUG|               SEP|               OCT|               NOV|               DEC|
+----+----+-----------------+------------------+------------------+------------------+------------------+------------------+------------------+------------------+------------------+------------------+------------------+------------------+
|NULL|NULL|18.42324786324786|20.137948717948717|23.434188034188036|26.514102564102565|28.386410256410255|28.300940170940162|27.369230769230775|26.940085470085464|26.342649572649577|24.742051282051282|21.765726495726508|19.173333333333332|
|   0|1901|            17.99|             19.43|             23.49|             26.41|             28.28|              28.6|             27.49|             26.98|             26.26|             25.08|             21.73|             18.95|
|   1|1902|             19.0|             20.39|              24.1|             26.54|             28.68|             28.44|             27.29|             27.05|             25.95|             24.37|             21.33|             18.78|
|   2|1903|            18.32|             19.79|             22.46|             26.03|             27.93|             28.41|             28.04|             26.63|             26.34|             24.57|             20.96|             18.29|
|   3|1904|            17.77|             19.39|             22.95|             26.73|             27.83|             27.85|             26.84|             26.73|             25.84|             24.36|             21.07|             18.84|
|   4|1905|             17.4|             17.79|             21.78|             24.84|             28.32|             28.69|             27.67|             27.47|             26.29|             26.16|             22.07|             18.71|
|   5|1906|             17.5|             19.14|             22.21|             26.53|             29.06|             28.02|             27.46|             26.82|             26.23|             24.75|             21.93|             19.55|
|   6|1907|            19.27|             19.42|             22.03|             26.98|             27.52|             27.66|             27.28|             26.38|             26.26|             24.72|             22.11|             18.46|
|   7|1908|            18.35|             19.73|             22.93|             27.06|             28.07|             28.49|             27.16|             26.41|             25.74|             24.25|             21.06|             18.15|
|   8|1909|            17.79|             19.05|              23.4|             25.76|             27.97|             27.67|             26.56|             26.43|             25.47|             24.37|             22.01|             18.86|
|   9|1910|            18.14|             19.72|              22.9|             25.96|             28.36|             27.72|             26.93|             26.61|             25.98|             24.04|             20.72|             18.05|
|  10|1911|            18.52|             19.18|             22.05|              26.0|             28.55|             28.02|             27.44|             27.04|             26.22|             24.57|              21.1|             18.76|
|  11|1912|             18.6|             20.84|             22.93|             26.21|              28.3|             28.53|             27.49|             26.68|             25.81|             24.44|              21.0|             18.44|
|  12|1913|             18.2|             19.98|             22.15|             26.61|             27.95|             27.91|              27.0|              26.8|             26.02|             24.35|             20.92|              18.7|
|  13|1914|            18.96|             19.66|             22.63|             25.73|             28.24|             28.46|             27.29|             26.49|             26.38|             23.97|             21.87|             18.73|
|  14|1915|            17.93|              19.0|             22.69|             26.23|             29.17|             28.58|             27.77|             27.32|             26.82|             25.46|             22.18|             18.31|
|  15|1916|            18.52|             19.68|             24.24|             26.84|             28.16|             27.81|             27.08|             26.77|              26.0|              24.6|             21.03|             18.17|
|  16|1917|            18.16|             19.94|             22.46|             25.29|             26.97|             27.41|             27.15|             26.64|             25.79|             23.85|              20.8|             18.39|
|  17|1918|            17.25|             19.58|             22.64|             25.26|             28.27|             27.58|             27.74|             26.97|              26.0|             24.54|             21.71|             18.37|
|  18|1919|            18.78|             19.15|             23.15|             26.19|              28.2|              28.3|             27.28|             26.84|             25.84|             24.36|             21.48|             18.58|
+----+----+-----------------+------------------+------------------+------------------+------------------+------------------+------------------+------------------+------------------+------------------+------------------+------------------+
only showing top 20 rows

Q3) Add columns Min and Max for each year with corresponding values

In [36]:
df3 = df1.withColumn("Min", least(*[col(month) for month in df.columns[2:13]]))
df3 = df3.withColumn("Max", greatest(*[col(month) for month in df.columns[2:13]]))
df3.show()

+---+----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-------------------+-----+-----+
|_c0|YEAR|  JAN|  FEB|  MAR|  APR|  MAY|  JUN|  JUL|  AUG|  SEP|  OCT|  NOV|  DEC|Average Temperature|  Min|  Max|
+---+----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-------------------+-----+-----+
|  0|1901|17.99|19.43|23.49|26.41|28.28| 28.6|27.49|26.98|26.26|25.08|21.73|18.95| 24.224166666666665|17.99| 28.6|
|  1|1902| 19.0|20.39| 24.1|26.54|28.68|28.44|27.29|27.05|25.95|24.37|21.33|18.78| 24.326666666666664| 19.0|28.68|
|  2|1903|18.32|19.79|22.46|26.03|27.93|28.41|28.04|26.63|26.34|24.57|20.96|18.29| 23.980833333333333|18.32|28.41|
|  3|1904|17.77|19.39|22.95|26.73|27.83|27.85|26.84|26.73|25.84|24.36|21.07|18.84| 23.849999999999998|17.77|27.85|
|  4|1905| 17.4|17.79|21.78|24.84|28.32|28.69|27.67|27.47|26.29|26.16|22.07|18.71|            23.9325| 17.4|28.69|
|  5|1906| 17.5|19.14|22.21|26.53|29.06|28.02|27.46|26.82|26.23|24.75|21.93|19.55| 24.099999999999998| 17.5|29.06|
|  6|1907|19.27|19.42|22.03|26.98|27.52|27.66|27.28|26.38|26.26|24.72|22.11|18.46| 24.007499999999997|19.27|27.66|
|  7|1908|18.35|19.73|22.93|27.06|28.07|28.49|27.16|26.41|25.74|24.25|21.06|18.15|              23.95|18.35|28.49|
|  8|1909|17.79|19.05| 23.4|25.76|27.97|27.67|26.56|26.43|25.47|24.37|22.01|18.86| 23.778333333333336|17.79|27.97|
|  9|1910|18.14|19.72| 22.9|25.96|28.36|27.72|26.93|26.61|25.98|24.04|20.72|18.05| 23.760833333333338|18.14|28.36|
| 10|1911|18.52|19.18|22.05| 26.0|28.55|28.02|27.44|27.04|26.22|24.57| 21.1|18.76| 23.954166666666666|18.52|28.55|
| 11|1912| 18.6|20.84|22.93|26.21| 28.3|28.53|27.49|26.68|25.81|24.44| 21.0|18.44| 24.105833333333337| 18.6|28.53|
| 12|1913| 18.2|19.98|22.15|26.61|27.95|27.91| 27.0| 26.8|26.02|24.35|20.92| 18.7| 23.882500000000004| 18.2|27.95|
| 13|1914|18.96|19.66|22.63|25.73|28.24|28.46|27.29|26.49|26.38|23.97|21.87|18.73| 24.034166666666668|18.96|28.46|
| 14|1915|17.93| 19.0|22.69|26.23|29.17|28.58|27.77|27.32|26.82|25.46|22.18|18.31| 24.288333333333338|17.93|29.17|
| 15|1916|18.52|19.68|24.24|26.84|28.16|27.81|27.08|26.77| 26.0| 24.6|21.03|18.17| 24.075000000000003|18.52|28.16|
| 16|1917|18.16|19.94|22.46|25.29|26.97|27.41|27.15|26.64|25.79|23.85| 20.8|18.39|  23.57083333333333|18.16|27.41|
| 17|1918|17.25|19.58|22.64|25.26|28.27|27.58|27.74|26.97| 26.0|24.54|21.71|18.37| 23.825833333333332|17.25|28.27|
| 18|1919|18.78|19.15|23.15|26.19| 28.2| 28.3|27.28|26.84|25.84|24.36|21.48|18.58| 24.012500000000003|18.78| 28.3|
| 19|1920|18.27|19.16|23.02|25.73|27.06|27.76|27.48|26.61|26.34|24.85|21.84|18.78|  23.90833333333333|18.27|27.76|
+---+----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-------------------+-----+-----+
only showing top 20 rows

Q4) Create dataframe called 'decade', storing average temperatures of each month in the respective
decade. Decade 1910 is from 1901 to 1910.

In [29]:
df = df.withColumn("Decade", (F.col("YEAR") / 10).cast("integer") * 10)
df.show()
decade_avg = df.groupBy("Decade").agg(*[F.avg(month).alias(month) for month in df.columns[2:]] ).orderBy("Decade", ascending = True)
decade_avg.show()

+---+----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+------+
|_c0|YEAR|  JAN|  FEB|  MAR|  APR|  MAY|  JUN|  JUL|  AUG|  SEP|  OCT|  NOV|  DEC|Decade|
+---+----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+------+
|  0|1901|17.99|19.43|23.49|26.41|28.28| 28.6|27.49|26.98|26.26|25.08|21.73|18.95|  1900|
|  1|1902| 19.0|20.39| 24.1|26.54|28.68|28.44|27.29|27.05|25.95|24.37|21.33|18.78|  1900|
|  2|1903|18.32|19.79|22.46|26.03|27.93|28.41|28.04|26.63|26.34|24.57|20.96|18.29|  1900|
|  3|1904|17.77|19.39|22.95|26.73|27.83|27.85|26.84|26.73|25.84|24.36|21.07|18.84|  1900|
|  4|1905| 17.4|17.79|21.78|24.84|28.32|28.69|27.67|27.47|26.29|26.16|22.07|18.71|  1900|
|  5|1906| 17.5|19.14|22.21|26.53|29.06|28.02|27.46|26.82|26.23|24.75|21.93|19.55|  1900|
|  6|1907|19.27|19.42|22.03|26.98|27.52|27.66|27.28|26.38|26.26|24.72|22.11|18.46|  1900|
|  7|1908|18.35|19.73|22.93|27.06|28.07|28.49|27.16|26.41|25.74|24.25|21.06|18.15|  1900|
|  8|1909|17.79|19.05| 23.4|25.76|27.97|27.67|26.56|26.43|25.47|24.37|22.01|18.86|  1900|
|  9|1910|18.14|19.72| 22.9|25.96|28.36|27.72|26.93|26.61|25.98|24.04|20.72|18.05|  1910|
| 10|1911|18.52|19.18|22.05| 26.0|28.55|28.02|27.44|27.04|26.22|24.57| 21.1|18.76|  1910|
| 11|1912| 18.6|20.84|22.93|26.21| 28.3|28.53|27.49|26.68|25.81|24.44| 21.0|18.44|  1910|
| 12|1913| 18.2|19.98|22.15|26.61|27.95|27.91| 27.0| 26.8|26.02|24.35|20.92| 18.7|  1910|
| 13|1914|18.96|19.66|22.63|25.73|28.24|28.46|27.29|26.49|26.38|23.97|21.87|18.73|  1910|
| 14|1915|17.93| 19.0|22.69|26.23|29.17|28.58|27.77|27.32|26.82|25.46|22.18|18.31|  1910|
| 15|1916|18.52|19.68|24.24|26.84|28.16|27.81|27.08|26.77| 26.0| 24.6|21.03|18.17|  1910|
| 16|1917|18.16|19.94|22.46|25.29|26.97|27.41|27.15|26.64|25.79|23.85| 20.8|18.39|  1910|
| 17|1918|17.25|19.58|22.64|25.26|28.27|27.58|27.74|26.97| 26.0|24.54|21.71|18.37|  1910|
| 18|1919|18.78|19.15|23.15|26.19| 28.2| 28.3|27.28|26.84|25.84|24.36|21.48|18.58|  1910|
| 19|1920|18.27|19.16|23.02|25.73|27.06|27.76|27.48|26.61|26.34|24.85|21.84|18.78|  1920|
+---+----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+------+
only showing top 20 rows

+------+------------------+------------------+------------------+------------------+------------------+------------------+------------------+------------------+------------------+------------------+------------------+------------------+------+
|Decade|               JAN|               FEB|               MAR|               APR|               MAY|               JUN|               JUL|               AUG|               SEP|               OCT|               NOV|               DEC|Decade|
+------+------------------+------------------+------------------+------------------+------------------+------------------+------------------+------------------+------------------+------------------+------------------+------------------+------+
|  1900|18.154444444444444| 19.34777777777778| 22.81666666666667|             26.32|28.184444444444445|28.203333333333337|             27.31|26.766666666666666| 26.04222222222222|24.736666666666668|21.585555555555555| 18.73222222222222|1900.0|
|  1910|            18.306|            19.673|            22.784|            26.032|28.217000000000002|            28.032|            27.317|26.816000000000003|26.085999999999995|            24.418|21.281000000000002|             18.45|1910.0|
|  1920|            18.271|            19.941|23.462000000000003|            26.462|            28.407|28.232999999999997|            27.296|            26.769|26.098000000000003|24.377999999999997|21.301000000000002|18.846999999999998|1920.0|
|  1930|18.162000000000003|19.857000000000003|            23.067|26.172999999999995|28.360000000000003|            28.117|            27.219|26.812000000000005|26.259999999999998|            24.517|            21.413|            18.983|1930.0|
|  1940|            18.144|            19.742|            23.213|              26.4|            28.551|28.359999999999996|27.347999999999995|26.928999999999995|26.264000000000003|24.700999999999997|            21.586|            19.005|1940.0|
|  1950|18.451999999999998|            20.018|            23.414|26.365999999999996|28.302999999999997|28.253999999999998|            27.162|26.768999999999995|26.259999999999998|24.505000000000003|21.502999999999993|            19.195|1950.0|
|  1960|            18.094|            20.213|            23.407|26.196999999999996|            27.956|28.279000000000003|27.270000000000003|26.870000000000005|26.241000000000003|            24.556|            21.631|19.090999999999998|1960.0|
|  1970|            18.291|19.865000000000002|            23.266|26.637999999999998|28.113999999999997|28.151999999999997|27.193999999999996|            26.725|26.189999999999998|            24.715|            21.807|            19.022|1970.0|
|  1980|            18.424|20.128999999999998|23.362000000000002|            26.537|            28.258|            28.311|27.334000000000003|26.982999999999997|            26.449|24.743000000000002|            21.736|            19.353|1980.0|
|  1990|            18.662|20.651999999999997|            23.636|26.514000000000003|28.413999999999998|28.485999999999997|27.512999999999998|            27.089|26.615999999999996|24.842999999999996|            22.161|            19.519|1990.0|
|  2000|            19.013|            20.935|24.214000000000006|            27.156|28.770999999999997|            28.417|27.666000000000004|            27.306|26.677000000000003|25.160999999999998|            22.457|            19.831|2000.0|
|  2010|           19.2425|             21.47|            24.775|27.565000000000005|            29.255|          28.87125|27.902500000000003|27.551250000000003|           27.0375|           25.8525|            22.945|          20.21625|2010.0|
+------+------------------+------------------+------------------+------------------+------------------+------------------+------------------+------------------+------------------+------------------+------------------+------------------+------+

Q5) Which year is the hottest year? (Based on avg temp)

In [31]:
hottest_year = df1.orderBy(F.desc("Average Temperature")).first()
coldest_year = df1.orderBy("Average Temperature").first()
print(f"Hottest Year: {hottest_year['YEAR']} with Average Temperature: {hottest_year['Average Temperature']:.2f}")
print(f"Coldest Year: {coldest_year['YEAR']} with Average Temperature: {coldest_year['Average Temperature']:.2f}")

Hottest Year: 2016 with Average Temperature: 26.45
Coldest Year: 1917 with Average Temperature: 23.57

Q6) Find out which years recorded minimum and maximum temperatures.

In [32]:
hottest_year = df3.orderBy(F.desc("Max")).first()
coldest_year = df3.orderBy("Min").first()
print(f"Hottest Year: {hottest_year['YEAR']} with Max Temperature: {hottest_year['Max']:.2f}")
print(f"Coldest Year: {coldest_year['YEAR']} with Min Temperature: {coldest_year['Min']:.2f}")

Hottest Year: 1921 with Max Temperature: 30.78
Coldest Year: 1918 with Min Temperature: 17.25

Q7) How much raise is observed in min and max temperature for each month?

In [37]:
df7 = df3.withColumn("Min_Difference", F.col("Min") - F.col("Average Temperature")) \
            .withColumn("Max_Difference", F.col("Max") - F.col("Average Temperature"))
df7_ = df7.select(
    "YEAR",
    "Min",
    "Max",
    "Average Temperature",
    "Min_Difference",
    "Max_Difference"
)
df7_.show()

+----+-----+-----+-------------------+-------------------+------------------+
|YEAR|  Min|  Max|Average Temperature|     Min_Difference|    Max_Difference|
+----+-----+-----+-------------------+-------------------+------------------+
|1901|17.99| 28.6| 24.224166666666665| -6.234166666666667| 4.375833333333336|
|1902| 19.0|28.68| 24.326666666666664| -5.326666666666664| 4.353333333333335|
|1903|18.32|28.41| 23.980833333333333| -5.660833333333333| 4.429166666666667|
|1904|17.77|27.85| 23.849999999999998| -6.079999999999998|4.0000000000000036|
|1905| 17.4|28.69|            23.9325| -6.532500000000002|            4.7575|
|1906| 17.5|29.06| 24.099999999999998| -6.599999999999998| 4.960000000000001|
|1907|19.27|27.66| 24.007499999999997| -4.737499999999997|3.6525000000000034|
|1908|18.35|28.49|              23.95| -5.599999999999998| 4.539999999999999|
|1909|17.79|27.97| 23.778333333333336| -5.988333333333337| 4.191666666666663|
|1910|18.14|28.36| 23.760833333333338| -5.620833333333337| 4.599166666666662|
|1911|18.52|28.55| 23.954166666666666| -5.434166666666666| 4.595833333333335|
|1912| 18.6|28.53| 24.105833333333337| -5.505833333333335| 4.424166666666665|
|1913| 18.2|27.95| 23.882500000000004|-5.6825000000000045|4.0674999999999955|
|1914|18.96|28.46| 24.034166666666668| -5.074166666666667| 4.425833333333333|
|1915|17.93|29.17| 24.288333333333338| -6.358333333333338| 4.881666666666664|
|1916|18.52|28.16| 24.075000000000003| -5.555000000000003| 4.084999999999997|
|1917|18.16|27.41|  23.57083333333333| -5.410833333333329| 3.839166666666671|
|1918|17.25|28.27| 23.825833333333332| -6.575833333333332| 4.444166666666668|
|1919|18.78| 28.3| 24.012500000000003| -5.232500000000002| 4.287499999999998|
|1920|18.27|27.76|  23.90833333333333| -5.638333333333332|  3.85166666666667|
+----+-----+-----+-------------------+-------------------+------------------+
only showing top 20 rows